services:
    app:
        image: sumitchai18241/e-commerce-digital
        container_name: e-commerce-digital
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            - PORT=${PORT}
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app/src
            - /app/node_modules
        depends_on:
            - mysql

    mysql:
        image: mysql
        # restart: always
        ports:
            - "3306:3306"
        volumes:
            - <your_mysql_data>:/var/lib/mysql
